name: "Test JSON"

inputs:
  images:
    description: "JSON array of containers and images to update in the task definition. Format: [{\"container-name\": \"name\", \"image\": \"uri\"}]"
    required: true


runs:
  using: composite

  steps:
    - name: Update ECS task definition with new image URIs ⚙️
      id: update-task-definition
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        INPUT_IMAGES: ${{ inputs.images }}
      with:
        script: |
          const imagesJson = JSON.parse(core.getInput('images'));
          
          console.log("imagesJson: ", imagesJson);
          console.log("imagesJson.length: ", imagesJson.length);
