version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/disallow-same-approver"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/cached-apt-get-install"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/optimize-apt-get"
    schedule:
      interval: "daily"
