name: "Package and upload to S3"
description: >
  Packages files or folders for every environment listed in the JSON config,
  using the AWS account, bucket, and role data defined there. Files or folders
  are zipped if needed, copied to S3, and later published through the
  Terraform → Lambda → CloudFront flow.
inputs:
  config:
    description: "JSON-encoded config (.gp.cicd.json)"
    required: true
  tag:
    description: "The main tag to apply to the artifact"
    required: true
  source-location:
    description: "A file or folder path"
    required: true
  source-type:
    description: "file | folder"
    required: true

outputs:
  result:
    description: The final tag value
    value: ${{ steps.record-tag.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Upload artifact to S3
      shell: bash --noprofile --norc -euo pipefail {0}
      id: upload-s3-artifact
      env:
        ACTION_PATH: ${{ github.action_path }}
        TZ: "Europe/Oslo"
        CONFIG: ${{ inputs.config }}
        PARTIAL_WORKFLOW_DISPATCH_URL: "${{ github.server_url}}/${{ github.repository }}/actions/workflows"
        SOURCE_TYPE: ${{ inputs.source-type }}
        SOURCE_LOCATION: ${{ inputs.source-location }}
        TAG: ${{ inputs.tag }}
      run: "$ACTION_PATH/scripts/upload-to-s3.sh"

    - name: Record artifact tag
      shell: bash --noprofile --norc -euo pipefail {0}
      id: record-tag
      run: |
        : "${ARTIFACT_TAG:?Missing ARTIFACT_TAG}"
        printf 'tag=%s\n' "$ARTIFACT_TAG" >>"$GITHUB_OUTPUT"

    - name: Store artifact tag in commit status
      shell: bash --noprofile --norc -euo pipefail {0}
      env:
        COMMIT_SHA: ${{ github.sha }}
        GH_TOKEN: ${{ github.token }}
        DESCRIPTION: ${{ steps.record-tag.outputs.tag }}
        WORKFLOW: ${{ github.workflow }}
        TARGET_URL: "${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      run: |
        gh api "repos/${GITHUB_REPOSITORY}/statuses/${COMMIT_SHA}" \
          -f state="success" \
          -f context="$WORKFLOW / artifact-tag" \
          -f target_url="$TARGET_URL" \
          -f description="$DESCRIPTION"
