name: Optimize apt (Advanced Packaging Tool)
description: Disables unnecessary apt features to optimize installation performance.

runs:

  using: composite

  steps:

    - name: Disable initramfs update
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
      shell: bash


    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update
      shell: bash


    - name: Disable fontconfig trigger
      run: sudo sed '/fontconfig/d' -i /var/lib/dpkg/triggers/File
      shell: bash


    - name: Disable install-info trigger
      run: sudo sed '/install-info/d' -i /var/lib/dpkg/triggers/File
      shell: bash


    - name: Disable mime related triggers
      run: sudo sed '/mime/d' -i /var/lib/dpkg/triggers/File
      shell: bash


    - name: Disable hicolor icon theme triggers
      run: sudo sed '/hicolor-icon-theme/d' -i /var/lib/dpkg/triggers/File
      shell: bash
