name: 'Renovate Metadata'
description: 'Check if PR is from Renovate and get update type'

inputs:
  skip-verification:
    description: 'Skip commit signature verification'
    required: false
    default: 'false'
  renovate-actor:
    description: 'GitHub username of the Renovate bot'
    required: false
    default: 'kjoremiljo-renovate[bot]'

outputs:
  is-renovate:
    description: 'Whether the PR is from Renovate'
    value: ${{ steps.check-author.outputs.is_renovate }}
  update-type:
    description: 'Renovate update type'
    value: ${{ steps.get-update-type.outputs.update_type }}

runs:
  using: "composite"
  steps:
    - name: Check actor
      id: check-author
      shell: bash
      run: |
        if [[ "${{ github.actor }}" == "${{ inputs.renovate-actor }}" ]]; then
          echo "is_renovate=true" >> $GITHUB_OUTPUT
        else
          echo "is_renovate=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        fetch-depth: 5

    - name: Verify commit signature
      if: ${{ inputs.skip-verification != 'true' }}
      shell: bash
      run: |
        git verify-commit HEAD^
      continue-on-error: true

    - name: Get update type
      id: get-update-type
      shell: bash
      run: |
        set -e
        RENOVATE_COMMIT=$(git log -n 5 --format="%H %s" | grep -m 1 "^[a-f0-9]\+ deps:" || true)
        if [ -z "$RENOVATE_COMMIT" ]; then
          echo "No Renovate commit found in the last 5 commits" >&2
          echo "update_type=unknown" >> $GITHUB_OUTPUT
          exit 0
        fi
        COMMIT_HASH=$(echo "$RENOVATE_COMMIT" | cut -d ' ' -f 1)
        COMMIT_MESSAGE=$(git log --format=%B -n 1 $COMMIT_HASH)
        UPDATE_TYPE=$(echo "$COMMIT_MESSAGE" | grep -oE '^(patch|minor|major)' || echo "unknown")
        echo "update_type=$UPDATE_TYPE" >> $GITHUB_OUTPUT
        echo "Detected update type: $UPDATE_TYPE"
        echo "Renovate commit: $COMMIT_HASH"
