name: "Package and upload artifact"
description: >
  Packages Docker images or files for every environment listed in the JSON config,
  using the AWS account, bucket, role, and repository data defined there. Docker
  sources are retagged and pushed to ECR so Terraform can deploy them to ECS. Files
  or folders are zipped if needed, copied to S3, and later published through the
  Terraform → Lambda → CloudFront flow.
inputs:
  config:
    description: "JSON-encoded config (.gp.cicd.json)"
    required: true
  tag:
    description: "The main tag to apply to the artifact"
    required: true
  source-location:
    description: "A Docker image ID, file or folder"
    required: true
  source-type:
    description: "docker-image | file | folder"
    required: true

outputs:
  result:
    description: The final tag value
    value: ${{ steps.upload.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Configure AWS credentials in dev
      if: ${{ fromJSON(inputs.config).dev != null }}
      id: aws-credentials-dev
      uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
      with:
        aws-region: ${{ fromJSON(inputs.config).dev.defaultRegion }}
        role-to-assume: ${{ fromJSON(inputs.config).dev.artifactRoleArn }}
        output-env-credentials: false
        output-credentials: true

    - name: Configure AWS credentials in prod
      if: ${{ fromJSON(inputs.config).prod != null }}
      id: aws-credentials-prod
      uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
      with:
        aws-region: ${{ fromJSON(inputs.config).prod.defaultRegion }}
        role-to-assume: ${{ fromJSON(inputs.config).prod.artifactRoleArn }}
        output-env-credentials: false
        output-credentials: true

    - name: Upload artifact to S3
      if: ${{ inputs.source-type == 'file' || inputs.source-type == 'folder' }}
      shell: bash --noprofile --norc -euo pipefail {0}
      id: upload-s3-artifact
      env:
        AWSCREDS: |
          [profile dev]
          aws_access_key_id=${{ steps.aws-credentials-dev.outputs.aws-access-key-id }}
          aws_secret_access_key=${{ steps.aws-credentials-dev.outputs.aws-secret-access-key }}
          aws_session_token=${{ steps.aws-credentials-dev.outputs.aws-session-token }}

          [profile prod]
          aws_access_key_id=${{ steps.aws-credentials-prod.outputs.aws-access-key-id }}
          aws_secret_access_key=${{ steps.aws-credentials-prod.outputs.aws-secret-access-key }}
          aws_session_token=${{ steps.aws-credentials-prod.outputs.aws-session-token }}
        TZ: "Europe/Oslo"
        CONFIG: ${{ inputs.config }}
        PARTIAL_WORKFLOW_DISPATCH_URL: "${{ github.server_url}}/${{ github.repository }}/actions/workflows"
        SOURCE_TYPE: ${{ inputs.source-type }}
        SOURCE_LOCATION: ${{ inputs.source-location }}
        TAG: ${{ inputs.tag }}
      run: package-and-upload-artifact/scripts/upload-s3-artifact.sh

    - name: Push Docker image to ECR
      if: ${{ inputs.source-type == 'docker-image' }}
      shell: bash --noprofile --norc -euo pipefail {0}
      id: push-ecr-image
      env:
        AWSCREDS: |
          [profile dev]
          aws_access_key_id=${{ steps.aws-credentials-dev.outputs.aws-access-key-id }}
          aws_secret_access_key=${{ steps.aws-credentials-dev.outputs.aws-secret-access-key }}
          aws_session_token=${{ steps.aws-credentials-dev.outputs.aws-session-token }}

          [profile prod]
          aws_access_key_id=${{ steps.aws-credentials-prod.outputs.aws-access-key-id }}
          aws_secret_access_key=${{ steps.aws-credentials-prod.outputs.aws-secret-access-key }}
          aws_session_token=${{ steps.aws-credentials-prod.outputs.aws-session-token }}
        TZ: "Europe/Oslo"
        CONFIG: ${{ inputs.config }}
        PARTIAL_WORKFLOW_DISPATCH_URL: "${{ github.server_url}}/${{ github.repository }}/actions/workflows"
        SOURCE_TYPE: ${{ inputs.source-type }}
        SOURCE_LOCATION: ${{ inputs.source-location }}
        TAG: ${{ inputs.tag }}
      run: package-and-upload-artifact/scripts/push-ecr-image.sh

    - name: Record artifact tag
      shell: bash --noprofile --norc -euo pipefail {0}
      id: upload
      run: |
        : "${ARTIFACT_TAG:?Missing ARTIFACT_TAG}"
        printf 'tag=%s\n' "$ARTIFACT_TAG" >>"$GITHUB_OUTPUT"
    - name: Store artifact tag in commit status
      shell: bash --noprofile --norc -euo pipefail {0}
      env:
        COMMIT_SHA: ${{ github.sha }}
        GH_TOKEN: ${{ github.token }}
        DESCRIPTION: ${{ steps.upload.outputs.tag }}
        WORKFLOW: ${{ github.workflow }}
        TARGET_URL: "${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      run: |
        gh api "repos/${GITHUB_REPOSITORY}/statuses/${COMMIT_SHA}" \
          -f state="success" \
          -f context="$WORKFLOW / artifact-tag" \
          -f target_url="$TARGET_URL" \
          -f description="$DESCRIPTION"
