name: "Determine Terraform stacks"
description: "Determine which Terraform stacks to run operations on"

inputs:
  selected-stacks:
    description: "Comma/newline-delimited list of stack patterns. Supports glob wildcards (*, **) and brace expansion ({a,b}). By default, only stacks with changed files are included."
    default: ""
    required: false
  ignored-stacks:
    description: "Comma/newline-delimited list of stack patterns to ignore. Supports glob wildcards (*, **) and brace expansion ({a,b})."
    default: ""
    required: false
  core-stacks:
    description: "Comma/newline-delimited list of stack patterns for core stacks. Supports glob wildcards (*, **) and brace expansion ({a,b}). If 'override-core-stacks' is true, replaces defaults."
    default: ""
    required: false
  override-core-stacks:
    description: "If true, replace the default core stack patterns with those provided in 'core-stacks' input. By default, 'core-stacks' is appended to a predefined list of patterns."
    default: "false"
    required: false

outputs:
  dev-core-stacks:
    description: "JSON array of dev core stacks (deployed sequentially in order)"
    value: ${{ steps.stacks.outputs.dev-core-stacks }}
  dev-apps-stacks:
    description: "JSON array of dev dependent stacks (deployed in parallel)"
    value: ${{ steps.stacks.outputs.dev-apps-stacks }}
  prod-core-stacks:
    description: "JSON array of prod core stacks (deployed sequentially in order)"
    value: ${{ steps.stacks.outputs.prod-core-stacks }}
  prod-apps-stacks:
    description: "JSON array of prod dependent stacks (deployed in parallel)"
    value: ${{ steps.stacks.outputs.prod-apps-stacks }}
  all-dev-stacks:
    description: "JSON array of all dev stacks"
    value: ${{ steps.stacks.outputs.all-dev-stacks }}
  all-prod-stacks:
    description: "JSON array of all prod stacks"
    value: ${{ steps.stacks.outputs.all-prod-stacks }}
  all-stacks:
    description: "JSON array of all stacks (dev and prod combined)"
    value: ${{ steps.stacks.outputs.all-stacks }}

runs:
  using: "composite"
  steps:
    - name: Detect changed stack files
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter
      if: ${{ inputs.selected-stacks == '' }}
      with:
        list-files: json
        filters: |
          all:
            - '**/*'

    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

    - name: Determine stacks
      id: stacks
      shell: bash --noprofile --norc -euo pipefail {0}
      env:
        SELECTED_STACKS: ${{ inputs.selected-stacks }}
        IGNORED_STACKS: ${{ inputs.ignored-stacks }}
        CORE_STACKS: ${{ inputs.core-stacks }}
        OVERRIDE_CORE_STACKS: ${{ inputs.override-core-stacks }}
        CHANGED_FILES: ${{ steps.filter.outcome == 'success' && join(fromJSON(steps.filter.outputs.all_files), ',') || '' }}
      run: |
        result="$(uv run "$GITHUB_ACTION_PATH/determine_stacks.py")"
        echo "Determined the following stacks:"
        echo "$result"
        echo "$result" >> "$GITHUB_OUTPUT"
