name: disallow-same-approver
description: Do not allow the person who initiated the deployment to approve it.

runs:

  using: composite

  steps:

    - name: Do not allow the person who initiated the deployment to approve it
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |

          const approvals = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/approvals', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          })

          const latestApproval = approvals.data[0];

          if (latestApproval.user.login == context.actor){
            core.setFailed(`The person who started the deployment (${context.actor}) is not allowed to approve it.`);
            return;
          }
