name: "Evaluate automerge"
description: "Evaluate whether Renovate upgrades to golden-path-boilerplate are safe to automerge"

inputs:
  rules:
    description: "JSON array of automerge rules. Each rule: {pattern, major?, minor?, patch?}. Policies: 'never', 'no-changes', 'any-changes'. First matching pattern wins. Unspecified types default to 'no-changes'."
    required: true
  stack-changes:
    description: "JSON object mapping stack paths to booleans (true = has Terraform changes)"
    required: true

outputs:
  automerge:
    description: "Whether the upgrades are safe to automerge ('true' or 'false')"
    value: ${{ steps.evaluate.outputs.automerge }}

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6

    - name: Evaluate automerge
      id: evaluate
      shell: bash --noprofile --norc -euo pipefail {0}
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        RULES: ${{ inputs.rules }}
        STACK_CHANGES: ${{ inputs.stack-changes }}
      run: |
        commit_message="$(gh api "repos/$GH_REPO/commits/$COMMIT_SHA" --jq '.commit.message')"
        automerge="$(uv run "$GITHUB_ACTION_PATH/evaluate_automerge.py" --commit-message "$commit_message" --rules "$RULES" --stack-changes "$STACK_CHANGES")"
        echo "automerge=$automerge" >> "$GITHUB_OUTPUT"
