name: "Verify release"
description: Verifies that a new release has been created successfully

inputs:
  release:
    description: The name of the release to verify
    required: true
  github-token:
    description: A GitHub token
    required: true


runs:

  using: composite

  steps:

    - name: Verify the new release
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        RELEASE: ${{ inputs.release }}
      # We need "bash {0}" to be able to catch errors without failing the step.
      # https://stackoverflow.com/questions/73066461/github-actions-why-an-intermediate-command-failure-in-shell-script-would-cause
      shell: bash {0}
      run: |
        IS_DRAFT=$(gh release view "$RELEASE" --json isDraft | jq '.isDraft')
        SUCCESS=$?

        if [[ $SUCCESS -ne 0 ]]; then
          echo "Release verification failed"
          gh release view "$RELEASE"
          exit 3
        fi

        if [[ $IS_DRAFT = "true" ]]; then
          echo "Release verification failed: Release is a draft but should be published"
          exit 4
        fi

        echo "Release '$RELEASE' was successfully published."
