name: "Crane copy image"

description: Copy a container image from one registry to another using Crane

inputs:
  aws-region:
    description: "AWS region"
    required: true
  ghcr-login:
    description: Login to the GitHub Container Registry (GHCR).
    required: false
    default: "false"
  token:
    description: "GitHub token"
    required: false
  aws-ecr-login:
    description: Log into AWS Elastic Container Registry (ECR).
    required: false
    default: "true"
  source-image:
    description: "Source image"
    required: true
  destination-image:
    description: "Destination image"
    required: true

runs:

  using: "composite"

  steps:

    - name: Add Homebrew to PATH
      shell: bash
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"


    - name: Install crane
      shell: bash
      run: |
        brew install crane


    - if: inputs.aws-ecr-login
      shell: bash
      name: Login to Elastic Container Registry (ECR) 🔑
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | \
          crane auth login \
            ${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com \
            --username AWS \
            --password-stdin


    - if: inputs.ghcr-login
      name: Login to GHCR 🔑
      shell: bash
      run: |
        echo ${{ inputs.token }} | \
          crane auth login \
            ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin


    - name: Copy image from source to destination
      shell: bash
      env:
        SOURCE_IMAGE: ${{ inputs.source-image }}
        DESTINATION_IMAGE: ${{ inputs.destination-image }}
      run: |
        crane copy "$SOURCE_IMAGE" "$DESTINATION_IMAGE"
