name: "Update and deploy ECS task definition"

description: "Downloads an existing ECS task definition, updates multiple container image URIs, and optionally deploys the updated task definition to the specified ECS service."

inputs:
  aws-region:
    description: "The AWS region to use."
    required: true

  aws-role-arn:
    description: "The ARN of the IAM role to assume."
    required: true

  cluster-name:
    description: "The name of the ECS service's cluster."
    required: true

  service-name:
    description: "The name of the ECS service to deploy to."
    required: true

  task-definition-name:
    description: "The name of the task definition."
    required: true

  images:
    description: "JSON array of containers and images to update in the task definition. Format: [{\"container-name\": \"name\", \"image\": \"uri\"}]"
    required: true

  deploy:
    description: "Deploy the task definition. Can be either \"true\" or \"false\"."
    required: true


outputs:
  task-definition-file-name:
    description: "The path to the rendered task definition file."
    value: "${{ steps.update-task-definition.outputs.task-definition }}"


runs:
  using: composite

  steps:
    - name: Configure AWS credentials using the OpenID Connect (OIDC) provider 🔑
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        aws-region: "${{ inputs.aws-region }}"
        role-to-assume: "${{ inputs.aws-role-arn }}"
        role-session-name: "${{ github.event.repository.name }}-gha-${{ github.run_id }}"


    - name: Login to Elastic Container Registry (ECR) 🔑
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1


    - name: Download existing ECS task definition ⚙️
      shell: bash
      run: |
        aws ecs describe-task-definition \
          --task-definition "${{ inputs.task-definition-name }}" \
          --query taskDefinition \
          | jq 'del(.registeredAt, .registeredBy, .compatibilities, .taskDefinitionArn, .requiresAttributes, .revision, .status)' > "task-definition.json"


    - name: Update ECS task definition with new image URIs ⚙️
      id: update-task-definition
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        INPUT_IMAGES: ${{ inputs.images }}
      with:
        script: |
          const fs = require('fs');
          
          // Set filenames
          const taskDefFile = 'task-definition.json';
          const outputTaskDefFile = 'updated-task-definition.json';
          
          // Read task definition
          const taskDef = JSON.parse(fs.readFileSync(taskDefFile, 'utf8'));
          
          // Get ECR registry URL from the ecr-login step
          const ecrRegistry = '${{ steps.ecr-login.outputs.registry }}';
          console.log(`Using ECR registry: ${ecrRegistry}`);
          
          // Parse images JSON
          const imagesInput = core.getInput('images');
          console.log("Images input", imagesInput);
          
          const imagesJson = JSON.parse(imagesInput);
          console.log(`Found ${imagesJson.length} container image(s) to update`);
          
          // Update container images
          imagesJson.forEach(imageConfig => {
            // Create full image URI with ECR registry
            const containerName = imageConfig['containerName'];
            const imageUri = `${ecrRegistry}/${imageConfig.image}`;
          
            console.log(`Updating container '${containerName}' with image '${imageUri}'`);
          
            // Find container in task definition
            const containerIndex = taskDef.containerDefinitions.findIndex(
              container => container.name === containerName
            );
          
            if (containerIndex >= 0) {
              // Update container image
              taskDef.containerDefinitions[containerIndex].image = imageUri;
              console.log(`Successfully updated container '${containerName}'`);
            } else {
              // Container not found
              core.warning(`Container '${containerName}' not found in task definition`);
            }
          });
          
          // Write updated task definition to file
          fs.writeFileSync(outputTaskDefFile, JSON.stringify(taskDef, null, 2));
          console.log('Task definition update complete');
          
          // Set output
          core.setOutput('task-definition', outputTaskDefFile);


    - if: inputs.deploy == 'true'
      name: Deploy task definition 🚀
      id: deploy
      uses: aws-actions/amazon-ecs-deploy-task-definition@8230edfe842008418c5275908cae75e51d3befb2 # v2.3.0
      with:
        cluster: "${{ inputs.cluster-name }}"
        service: "${{ inputs.service-name }}"
        task-definition: "${{ steps.update-task-definition.outputs.task-definition }}"
        wait-for-service-stability: true


    - name: Write deployment summary 📝
      shell: bash
      env:
        IMAGES_JSON: ${{ inputs.images }}
        SERVICE_NAME: ${{ inputs.service-name }}
        TASK_DEFINITION_NAME: ${{ inputs.task-definition-name }}
        DEPLOY: ${{ inputs.deploy }}
      run: |
#        # Example values to be used for testing in a local script:
#        GITHUB_STEP_SUMMARY="/dev/stdout"
#        IMAGES_JSON='[{"containerName":"flyway","imageRepository":"flyway","imageDigest":"sha256:0d4626f3160ffcb561926074c0c3305a0faa7955","imageVersion":"2025-03-06_16-27-31_main_gha-13703418764_sha-b8a861e"},{"containerName":"too-tikki","imageRepository":"pirates-dev-too-tikki","imageDigest":"sha256:c5777a8d16b664157b5ac56196f70527f1ce10e1","imageVersion":"2025-03-06_16-27-31_main_gha-13703418764_sha-b8a861e"}]'
#        SERVICE_NAME='too-tikki'
#        TASK_DEFINITION_NAME='too-tikki'
#        DEPLOY='true'
        
        # Count the number of images being deployed
        IMAGE_COUNT=$(echo "$IMAGES_JSON" | jq 'if type == "array" then length else 1 end')
        
        echo "## Deployment summary 📋" >> $GITHUB_STEP_SUMMARY
        
        # Add summary statement below title
        if [[ "$DEPLOY" == "true" ]]; then
          echo "✅ Updated task definition \`$TASK_DEFINITION_NAME\` with $IMAGE_COUNT container image(s) and deployed to ECS service \`$SERVICE_NAME\`." >> $GITHUB_STEP_SUMMARY
        else
          echo "Updated task definition \`$TASK_DEFINITION_NAME\` with $IMAGE_COUNT container image(s). **No deployment was performed.**" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "### Containers(s) 📦" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Parse and display container images in a table with all fields
        echo "| Container | Repository | Digest | Tag |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
        
        # Handle both array and single object cases and format both digest and version as code
        echo "$IMAGES_JSON" | jq -r 'if type == "array" then .[] else . end | "| \(.containerName) | \(.imageRepository) | `\(.imageDigest)` | `\(.imageVersion)` |"' >> $GITHUB_STEP_SUMMARY
        
        echo "" >> $GITHUB_STEP_SUMMARY
