name: ci

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    # NOTE: A bit stricter than the default bash options used by GitHub Actions
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  test-determine-stacks:
    name: Test determine-stacks composite action
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Run tests
        working-directory: ./determine-stacks
        run: uv run pytest -v

  test-build-gp-config:
    name: Test build-gp-config composite action
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Run tests
        working-directory: ./build-gp-config
        run: make test

      - name: Run build-gp-config action
        id: build
        uses: ./build-gp-config
        with:
          # The config file and schema used don't need to be the actual config or schema. We just want to test that the
          # composite action can output a valid config.
          config-file: build-gp-config/testdata-ci/dummy-config.json
          app-name: hello-world
          stack-name: app-hello-world

      - name: Verify output
        env:
          CONFIG: ${{ steps.build.outputs.config }}
        run: |
          echo "$CONFIG"
          test "$(echo "$CONFIG" | jq -r '.appName')" = "hello-world"
          test "$(echo "$CONFIG" | jq -r '.dev.stackDir')" = "stacks/dev/app-hello-world"
          test "$(echo "$CONFIG" | jq -r '.dev.concurrencyGroup')" = "test-dev-hello-world"

      - name: Run build-gp-config action (invalid config)
        id: build-invalid
        uses: ./build-gp-config
        continue-on-error: true
        with:
          config-file: build-gp-config/testdata-ci/invalid-config.json
          app-name: hello-world
          stack-name: app-hello-world

      - name: Verify invalid config was rejected
        run: test "${{ steps.build-invalid.outcome }}" = "failure"

  test-evaluate-automerge:
    name: Test evaluate-automerge composite action
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Run tests
        working-directory: ./evaluate-automerge
        run: make test
