name: Super-Linter

on:

  workflow_dispatch:

  pull_request:

  push:
    branches:
      - main


jobs:

  lint:

    # https://github.com/oslokommune/reusable-workflows/blob/main/.github/workflows/superlinter.yml
    name: Run Super-Linter
    uses: oslokommune/reusable-workflows/.github/workflows/superlinter.yml@main
    secrets: inherit
