name: Test setup-ok

on:

  workflow_dispatch:

jobs:

  test:

    name: Test setup-boilerplate

    runs-on: ubuntu-latest

    steps:

      - name: Run setup-ok composite action
        uses: oslokommune/composite-actions/setup-ok@38285c293e361b0f32a68a245c429adc3c5ff25b # main
