name: Test setup-ok

on:

  workflow_dispatch:

jobs:

  test:

    name: Test setup-boilerplate

    runs-on: ubuntu-latest

    steps:

      - name: Run setup-ok composite action
        uses: oslokommune/composite-actions/setup-ok@bdba791d662bb8d48b2f1105430a01cde846277b # main
