name: Test repository-dispatch

on:

  workflow_dispatch:

jobs:

  test:

    name: Test repository-dispatch

    runs-on: ubuntu-latest

    steps:

      - name: Run repository-dispatch composite action
        uses: oslokommune/composite-actions/repository-dispatch@main
        with:
          event_type: something
          client_payload: >
            {
              "id": "something",
              "sender_repository": "${{ github.repository }}",
              "sender_run_id": "${{ github.run_id }}"
            }
