name: Test disallow-same-approver

on:

  workflow_dispatch:

jobs:

  test:

    name: Test disallow-same-approver

    runs-on: ubuntu-latest
    environment: test

    steps:

      - name: Run disallow-same-approver composite action
        uses: oslokommune/composite-actions/disallow-same-approver@e89ad5e146afba36f3f8a89db9d94685bb60adc4 # main
