name: Test disallow-same-approver

on:

  workflow_dispatch:

jobs:

  test:

    name: Test disallow-same-approver

    runs-on: ubuntu-latest
    environment: test

    steps:

      - name: Run disallow-same-approver composite action
        uses: oslokommune/composite-actions/disallow-same-approver@99f346dc4483995035a85913a9cf0fd6e76dfd89 # main
