name: Test setup-ok

on:

  workflow_dispatch:

jobs:

  test:

    name: Test setup-boilerplate

    runs-on: ubuntu-latest

    steps:

      - name: Run setup-ok composite action
        uses: oslokommune/composite-actions/setup-ok@99f346dc4483995035a85913a9cf0fd6e76dfd89 # main
