name: Test setup-boilerplate

on:

  workflow_dispatch:

jobs:

  test:

    name: Test setup-boilerplate

    runs-on: ubuntu-latest

    steps:

      - name: Run setup-boilerplate composite action
        uses: oslokommune/composite-actions/setup-boilerplate@55ee2c7bef4b80f4535761f03b8f3d07e064836f # main
